package com.taha.newraapp.domain.repository

import com.taha.newraapp.data.model.response.InitiateCallResponse

/**
 * Repository interface for call-related operations.
 */
interface CallRepository {
    /**
     * Initiate a call to another user.
     * 
     * @param calleeId The ID of the user being called
     * @param roomId The LiveKit room ID (generated by caller)
     * @param callType The type of call: "audio" or "video"
     * @return Result containing InitiateCallResponse on success
     */
    suspend fun initiateCall(
        calleeId: String,
        roomId: String,
        callType: String
    ): Result<InitiateCallResponse>
}
